# Generated by Django 5.0.14 on 2026-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kampus', models.CharField(max_length=255, verbose_name='Nama Kampus')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('kontak', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontak / Telepon')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('NONAKTIF', 'Nonaktif')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kampus',
                'ordering': ['nama_kampus'],
            },
        ),
    ]
