# Generated by Django 5.0.14 on 2026-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kampus',
            name='fakultas',
            field=models.TextField(blank=True, null=True, verbose_name='Fakultas'),
        ),
        migrations.AddField(
            model_name='kampus',
            name='prodi',
            field=models.TextField(blank=True, null=True, verbose_name='Program Studi'),
        ),
    ]
