# Generated by Django 5.0.14 on 2026-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Absen')),
                ('jam_masuk', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('jam_pulang', models.TimeField(blank=True, null=True, verbose_name='Jam Pulang')),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALPA', 'Alpa')], default='HADIR', max_length=20)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('foto_masuk', models.ImageField(blank=True, null=True, upload_to='foto_absensi/', verbose_name='Foto Masuk')),
                ('foto_pulang', models.ImageField(blank=True, null=True, upload_to='foto_absensi/', verbose_name='Foto Pulang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Absensi',
                'ordering': ['-tanggal', '-jam_masuk'],
            },
        ),
    ]
