# Generated by Django 5.0.14 on 2026-08-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absensi', '0001_initial'),
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_list', to='mahasiswa.mahasiswa'),
        ),
        migrations.AlterUniqueTogether(
            name='absensi',
            unique_together={('mahasiswa', 'tanggal')},
        ),
    ]
