# Generated by Django 5.0.14 on 2026-08-11 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
                ('bagian', models.CharField(max_length=150, verbose_name='Bagian / Unit BGTK')),
                ('status', models.CharField(choices=[('BELUM_MULAI', 'Belum Mulai'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_magang', to='mahasiswa.mahasiswa')),
                ('pembimbing', models.ForeignKey(blank=True, limit_choices_to={'role': 'PEMBIMBING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_magang_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Magang',
                'ordering': ['-tanggal_mulai'],
            },
        ),
    ]
