# Generated by Django 5.0.14 on 2026-08-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Laporan Akhir')),
                ('kata_pengantar', models.TextField(blank=True, null=True, verbose_name='Kata Pengantar')),
                ('latar_belakang', models.TextField(blank=True, null=True, verbose_name='BAB I - Latar Belakang')),
                ('tujuan', models.TextField(blank=True, null=True, verbose_name='BAB I - Tujuan Magang')),
                ('manfaat', models.TextField(blank=True, null=True, verbose_name='BAB I - Manfaat Magang')),
                ('gambaran_umum', models.TextField(blank=True, null=True, verbose_name='BAB II - Gambaran Umum BGTK Sumbar')),
                ('pelaksanaan_magang', models.TextField(blank=True, null=True, verbose_name='BAB III - Pelaksanaan Magang')),
                ('hasil_pembahasan', models.TextField(blank=True, null=True, verbose_name='BAB IV - Hasil & Pembahasan')),
                ('kesimpulan', models.TextField(blank=True, null=True, verbose_name='BAB V - Kesimpulan')),
                ('saran', models.TextField(blank=True, null=True, verbose_name='BAB V - Saran')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='laporan/pdf/', verbose_name='File PDF')),
                ('file_word', models.FileField(blank=True, null=True, upload_to='laporan/word/', verbose_name='File Word (.docx)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PERIKSA', 'Menunggu Pemeriksaan'), ('DISETUJUI', 'Disetujui'), ('PERLU_REVISI', 'Perlu Revisi')], default='DRAFT', max_length=20)),
                ('catatan_pembimbing', models.TextField(blank=True, null=True, verbose_name='Catatan Pembimbing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_akhir', to='mahasiswa.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Laporan Akhir',
                'ordering': ['-updated_at'],
            },
        ),
    ]
