# Generated by Django 5.0.14 on 2026-08-11 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KegiatanHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Kegiatan')),
                ('judul_kegiatan', models.CharField(max_length=200, verbose_name='Judul Kegiatan')),
                ('kegiatan', models.TextField(verbose_name='Uraian Kegiatan')),
                ('hasil', models.TextField(verbose_name='Hasil Kegiatan')),
                ('kendala', models.TextField(blank=True, default='Tidak ada kendala', verbose_name='Kendala')),
                ('solusi', models.TextField(blank=True, default='Tidak ada', verbose_name='Solusi')),
                ('dokumentasi', models.ImageField(blank=True, null=True, upload_to='dokumentasi_kegiatan/', verbose_name='Dokumentasi Foto')),
                ('status_verifikasi', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak'), ('PERLU_REVISI', 'Perlu Revisi')], default='MENUNGGU', max_length=20)),
                ('komentar_pembimbing', models.TextField(blank=True, null=True, verbose_name='Komentar Pembimbing')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan_harian_list', to='mahasiswa.mahasiswa')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kegiatan_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kegiatan Harian',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KegiatanBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField(verbose_name='Bulan (1-12)')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('ringkasan', models.TextField(verbose_name='Ringkasan Kegiatan Bulanan')),
                ('total_hadir', models.IntegerField(default=0)),
                ('total_kegiatan', models.IntegerField(default=0)),
                ('total_disetujui', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_bulanan_list', to='mahasiswa.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Kegiatan Bulanan',
                'ordering': ['-tahun', '-bulan'],
                'unique_together': {('mahasiswa', 'bulan', 'tahun')},
            },
        ),
    ]
