# Generated by Django 5.0.14 on 2026-08-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatanharian',
            name='minggu_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Minggu Mulai'),
        ),
        migrations.AddField(
            model_name='kegiatanharian',
            name='minggu_selesai',
            field=models.DateField(blank=True, null=True, verbose_name='Minggu Selesai'),
        ),
    ]
