# Generated by Django 5.0.14 on 2026-08-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_kegiatanharian_minggu_mulai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kegiatanharian',
            options={'ordering': ['-tanggal', '-created_at'], 'verbose_name_plural': 'Kegiatan Mingguan'},
        ),
    ]
