# Generated by Django 5.0.14 on 2026-08-11 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kampus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=50, unique=True, verbose_name='NIM')),
                ('prodi', models.CharField(max_length=150, verbose_name='Program Studi')),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor HP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_mahasiswa/', verbose_name='Foto Profile')),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('SELESAI', 'Selesai'), ('NONAKTIF', 'Nonaktif')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kampus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_list', to='kampus.kampus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
                'ordering': ['user__first_name', 'nim'],
            },
        ),
    ]
